package com.huruwo.mapview.mapview;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.huruwo.mapview.mapview.MapBean;
import com.huruwo.mapview.mapview.PathItem;

import com.huruwo.mapview.mapview.MapBeanDao;
import com.huruwo.mapview.mapview.PathItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mapBeanDaoConfig;
    private final DaoConfig pathItemDaoConfig;

    private final MapBeanDao mapBeanDao;
    private final PathItemDao pathItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mapBeanDaoConfig = daoConfigMap.get(MapBeanDao.class).clone();
        mapBeanDaoConfig.initIdentityScope(type);

        pathItemDaoConfig = daoConfigMap.get(PathItemDao.class).clone();
        pathItemDaoConfig.initIdentityScope(type);

        mapBeanDao = new MapBeanDao(mapBeanDaoConfig, this);
        pathItemDao = new PathItemDao(pathItemDaoConfig, this);

        registerDao(MapBean.class, mapBeanDao);
        registerDao(PathItem.class, pathItemDao);
    }
    
    public void clear() {
        mapBeanDaoConfig.clearIdentityScope();
        pathItemDaoConfig.clearIdentityScope();
    }

    public MapBeanDao getMapBeanDao() {
        return mapBeanDao;
    }

    public PathItemDao getPathItemDao() {
        return pathItemDao;
    }

}
