package com.huruwo.mapview.mapview;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MAP_BEAN".
*/
public class MapBeanDao extends AbstractDao<MapBean, Long> {

    public static final String TABLENAME = "MAP_BEAN";

    /**
     * Properties of entity MapBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Map_name = new Property(1, String.class, "map_name", false, "MAP_NAME");
        public final static Property Map_w = new Property(2, float.class, "map_w", false, "MAP_W");
        public final static Property Map_h = new Property(3, float.class, "map_h", false, "MAP_H");
    }

    private DaoSession daoSession;


    public MapBeanDao(DaoConfig config) {
        super(config);
    }
    
    public MapBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MAP_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MAP_NAME\" TEXT UNIQUE ," + // 1: map_name
                "\"MAP_W\" REAL NOT NULL ," + // 2: map_w
                "\"MAP_H\" REAL NOT NULL );"); // 3: map_h
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MAP_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MapBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String map_name = entity.getMap_name();
        if (map_name != null) {
            stmt.bindString(2, map_name);
        }
        stmt.bindDouble(3, entity.getMap_w());
        stmt.bindDouble(4, entity.getMap_h());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MapBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String map_name = entity.getMap_name();
        if (map_name != null) {
            stmt.bindString(2, map_name);
        }
        stmt.bindDouble(3, entity.getMap_w());
        stmt.bindDouble(4, entity.getMap_h());
    }

    @Override
    protected final void attachEntity(MapBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MapBean readEntity(Cursor cursor, int offset) {
        MapBean entity = new MapBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // map_name
            cursor.getFloat(offset + 2), // map_w
            cursor.getFloat(offset + 3) // map_h
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MapBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMap_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMap_w(cursor.getFloat(offset + 2));
        entity.setMap_h(cursor.getFloat(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MapBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MapBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MapBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
